FROM python:3.12.1

# Set the working directory inside the container
WORKDIR /app

# Copy everything from current directory to /app in container
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your Flask app runs on
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]
